server:
  port: 8083

mybatis:
  type-aliases-package: com.zh.springbootdocker.entity
  mapper-locations: classpath:sqlmap/*.xml

spring:
  datasource:
    username: zhangqiang
    password: A%277708272
    url: jdbc:mysql://39.96.165.167:3306/zhangqiang?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver